export const projects = [
    {
      title: 'SMS Service System',
      description: "This app allows you to send and receive SMS messages to and from any country in the world.",
        image: '/images/sms.png',
        tags: ['Mongodb', 'Express' ,'Material-UI', 'NextJs','typescrpt','Nodejs'],
      source: 'https://github.com/Airdady/fe-sms-main',
      visit: 'https://fe-sms-main.vercel.app/',
      id: 0,
    },
    {
      title: 'Mentorship Hub',
      description:"The Stage is a mentorship hub to spark collaboration and celebrate champions of social change in Uganda.",
      image: '/images/theStage.png',
      tags: ['Reactjs', 'CSS3'],
      source: 'https://bitbucket.org/unfpasocent/unfpasocialenterprisehub/src/master/',
      visit: 'https://www.thestageug.org',
      id: 1,
    },
    {
      title: 'SMS ServiceSystem Dashboad',
      description: "Each message is identified by a unique random ID so that users can always check the status of a message using the given endpoint.",
        image: '/images/admin.png',
        tags: ['Reactjs', 'Ant-Design','Redux Toolkit'],
      source: 'https://github.com/Airdady/fe-sms-admin',
      visit: 'https://api.sms.airdady.com',
      id: 2,
    },
    {
      title: 'Restaurant App',
      description: "The Restaurant app was can allow a user to search for different dishes and the ingredients used.",
      image: '/images/restaurant.png',
      tags: ['Reactjs', 'CSS3', 'https://api.edamam.com'],
      source: 'https://github.com/Ayesiza/restaurant-react',
      visit: 'https://github.com/Ayesiza/restaurant-react',
      id: 3,
    },
    {
        title: 'Property Pro-Lite',
        description: "Property Pro Lite is a platform where people can create and/or search properties for sale or rent.",
          image: '/images/property.png',
          tags: ['HTML5', 'CSS3','Javascript','NodeJs'],
        source: 'https://github.com/Ayesiza/Property-Pro-lite',
        visit: 'https://ayesiza.github.io/Property-Pro-lite/index.html',
        id: 4,
      },
      {
        title: 'Free Mentor',
        description:"Free Mentors is a social initiative where  professionals become role models to young people to provide free mentorship sessions.",
        image: '/images/freementor.png',
        tags: ['Nodejs','HTML5','CSS' ,'JavaScript'],
        source: 'https://github.com/Ayesiza/Free-mentors-API',
        visit: 'https://ayesiza.github.io/Free-Mentors/',
        id: 5,
      },
  ];
  